// Fictional browser fixtures only. Never inserted in Supabase.
export const heroes = [
  {
    id: 1,
    display_name: "Arjun",
    class_key: "mage",
    level: 18,
    xp: 12480,
    streak: 21,
    reputation: 380,
    helpful: 42,
    solved: 12,
    guild_name: "Code Warriors",
    guild_id: 1,
    score: 380,
    rank: 1,
  },
  {
    id: 2,
    display_name: "Priya",
    class_key: "knight",
    level: 17,
    xp: 11020,
    streak: 18,
    reputation: 340,
    helpful: 38,
    solved: 10,
    guild_name: "The Early Birds",
    guild_id: 2,
    score: 340,
    rank: 2,
  },
  {
    id: 3,
    display_name: "Rahul",
    class_key: "ranger",
    level: 16,
    xp: 10020,
    streak: 15,
    reputation: 310,
    helpful: 34,
    solved: 9,
    guild_name: "Code Warriors",
    guild_id: 1,
    score: 310,
    rank: 3,
  },
  {
    id: 12,
    display_name: "Kunal",
    class_key: "knight",
    level: 12,
    xp: 7240,
    streak: 14,
    reputation: 255,
    helpful: 31,
    solved: 8,
    guild_name: "Code Warriors",
    guild_id: 1,
    score: 255,
    rank: 4,
    movement: 2,
    best: true,
  },
  ...["Aman", "Riya", "Ananya", "Dev"].map((name, i) => ({
    id: 30 + i,
    display_name: name,
    class_key: ["bard", "mage", "ranger", "knight"][i],
    level: 12 - i,
    xp: 5000 - i * 100,
    streak: 8 + i,
    reputation: 220 - i * 10,
    helpful: 29 - i * 3,
    solved: 6,
    guild_name: null,
    guild_id: null,
    score: 220 - i * 10,
    rank: 5 + i,
  })),
];
export const posts = [
  {
    id: 1,
    author_id: 12,
    display_name: "Kunal",
    class_key: "knight",
    xp: 7240,
    post_type: "help",
    title: "I know what to study. How do I actually stay consistent?",
    content:
      "I start DSA with so much energy every Monday, but by Thursday I’ve fallen off. I’ve tried strict timetables, but they never seem to stick. What helped you build a rhythm that lasts?",
    tried: "A strict two-hour timetable every day.",
    tags: ["dsa", "consistency", "study"],
    is_solved: false,
    comment_count: 8,
    reaction_count: 12,
  },
  {
    id: 2,
    author_id: 2,
    display_name: "Priya",
    class_key: "knight",
    xp: 11020,
    post_type: "tip",
    title: "The two-minute rule finally made reading a habit.",
    content:
      "Instead of promising myself a whole chapter, I started with just one page. Six weeks later, I’m still showing up. Here’s what changed.",
    tags: ["reading", "habits"],
    is_solved: false,
    comment_count: 4,
    reaction_count: 19,
  },
  {
    id: 3,
    author_id: 1,
    display_name: "Arjun",
    class_key: "mage",
    xp: 12480,
    post_type: "achievement",
    title: "30 days of showing up. Not perfectly. Just consistently.",
    content:
      "Some sessions were ten minutes. Some were an hour. Every one of them counted. A small victory worth sharing with the people who helped me get here.",
    tags: ["small-wins"],
    is_solved: false,
    comment_count: 6,
    reaction_count: 24,
  },
  {
    id: 4,
    author_id: 3,
    display_name: "Rahul",
    class_key: "ranger",
    xp: 10020,
    post_type: "question",
    title: "How do you switch off after a long day of coding?",
    content:
      "Thank you to everyone who shared their evening rituals. A short walk and a screen-free dinner have made a surprising difference.",
    tags: ["wellbeing", "focus"],
    is_solved: true,
    comment_count: 5,
    reaction_count: 9,
  },
].map((p, i) => ({
  ...p,
  created_at: new Date(Date.now() - (i + 1) * 3600000).toISOString(),
  saved: false,
  reactions: [],
  guild_name: null,
  guild_id: null,
  solved_comment_id: p.is_solved ? 1 : null,
  category: null,
}));
export const guilds = [
  {
    id: 1,
    name: "Code Warriors",
    slug: "code-warriors",
    description:
      "One problem at a time. A home for curious minds and steady progress.",
    emblem: "🛡️",
    visibility: "public",
    xp: 2450,
    weekly_xp: 450,
    level: 5,
    member_count: 48,
    role: "owner",
  },
  {
    id: 2,
    name: "The Early Birds",
    slug: "early-birds",
    description:
      "A little sunlight, a morning walk, and a gentle head start on the day.",
    emblem: "🌿",
    visibility: "public",
    xp: 1820,
    weekly_xp: 320,
    level: 4,
    member_count: 27,
    role: null,
  },
  {
    id: 3,
    name: "The Quiet Chapter",
    slug: "quiet-chapter",
    description:
      "For the readers, the thinkers, and the just-one-more-page adventurers.",
    emblem: "📚",
    visibility: "invite_only",
    xp: 1120,
    weekly_xp: 220,
    level: 3,
    member_count: 16,
    role: null,
  },
];
export const quests = [
  {
    id: 1,
    guild_id: 1,
    title: "The seven-day coding quest",
    description:
      "Make room for one focused session. Together, we’re working toward 50 sessions of real-life progress.",
    icon: "⚔️",
    target: 50,
    progress: 41,
    status: "active",
    starts_at: "2026-09-10T00:00:00Z",
    ends_at: "2026-09-20T00:00:00Z",
    reward_xp: 500,
    reward_gold: 50,
    reward_reputation: 5,
    attribute: "intellect",
    joined: true,
    contribution: 7,
    reward_claimed: false,
    participants: 24,
  },
];
export const challenges = [
  {
    ...quests[0],
    id: 2,
    title: "A week of small beginnings",
    description:
      "A thousand focused sessions. One supportive community. Bring your everyday quests to this shared adventure.",
    metric: "sessions",
    target: 1000,
    progress: 682,
    reward_xp: 100,
    attribute: null,
    joined: false,
    participants: 124,
  },
  {
    ...quests[0],
    id: 3,
    title: "The morning light quest",
    description:
      "Not a perfect streak. Just a community of people choosing to show up, one day at a time.",
    metric: "streak_days",
    target: 500,
    progress: 328,
    reward_xp: 100,
    attribute: null,
    participants: 87,
  },
  {
    ...quests[0],
    id: 4,
    title: "One hundred brave beginnings",
    description:
      "Every hero who completes a quest moves us forward. There’s room for you here.",
    metric: "members",
    target: 100,
    progress: 100,
    reward_xp: 100,
    status: "completed",
    attribute: null,
    participants: 100,
    contribution: 1,
    reward_claimed: false,
  },
];
export const comments = [
  {
    id: 1,
    post_id: 1,
    author_id: 2,
    display_name: "Priya",
    class_key: "knight",
    content:
      "Start smaller than you think you need to. Ten minutes after breakfast is easier to repeat than a perfect two-hour block. Build trust in the routine first.",
    parent_comment_id: null,
    is_solution: false,
    depth: 1,
    helpful_count: 4,
    reactions: [],
    created_at: new Date().toISOString(),
    deleted_at: null,
  },
  {
    id: 2,
    post_id: 1,
    author_id: 1,
    display_name: "Arjun",
    class_key: "mage",
    content:
      "This helped me too. I put my notebook next to the kettle so there’s a visible reminder.",
    parent_comment_id: 1,
    is_solution: false,
    depth: 2,
    helpful_count: 2,
    reactions: [],
    created_at: new Date().toISOString(),
    deleted_at: null,
  },
];
